### ISSUE TITLE
deployuVirtualMachine

### ISSUE THREAD

**Issue by BwOrK** [PCextreme/cloudstack-php#1]
when I am trying to deploy a VM via API call I am not able to correctl transfer array which is containing the 
networks id to a variable  "iptonetworklist"

can you tell me how to do it,

$cloudQuery = $this->cloudConnect->clientEurope()->command(......)
 
let me know
Thansk

**Comment by kevindierkx** [comment]
@BwOrK If I'm not mistaken you only get a jobId from the deployVirtualMachine command. You can use this to query the async job result (`queryAsyncjobresult`). When the job succeeds there should be a nics array in the virtual machine response.

**Comment by kevindierkx** [comment]
Closing this issue, can't reproduce the issue.
