### ISSUE TITLE
Use of deprecated function

### ISSUE THREAD

**Issue by FrontEndCoffee** [PCextreme/cloudstack-php#9]
During a PR build, something came up.

On 7.2, PHP throws warnings because of the use of the deprecated `count()` function in this codebase.

See: [TravisCI build](https://travis-ci.org/PCextreme/cloudstack-php/jobs/438521147)

Please patch this code so we don't use `count()` any longer.

**Comment by kevindierkx** [comment]
Fixed in PR#12
